-- Insert sample promotions for testing

-- Sample 1: Welcome Discount for New Customers
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Welcome to Meetmydesigners!',
  'Get 20% off your first design session with any of our talented designers. Start your creative journey today!',
  'discount',
  'percentage',
  20.00,
  'WELCOME20',
  500.00,
  1000.00,
  100,
  now(),
  now() + interval '30 days',
  'new_users',
  ARRAY['homepage', 'designers'],
  5,
  '#ffffff',
  '#16a34a',
  'Get Started',
  '/designers',
  'Welcome promotion for new customers - 20% off first session'
);

-- Sample 2: Flash Sale Announcement
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Flash Sale - 50% Off All Sessions!',
  'Limited time offer! Get 50% off on all design sessions. Book now before it ends!',
  'discount',
  'percentage',
  50.00,
  'FLASH50',
  1000.00,
  2000.00,
  50,
  now(),
  now() + interval '7 days',
  'all',
  ARRAY['homepage', 'designers', 'services'],
  10,
  '#ffffff',
  '#dc2626',
  'Book Now',
  '/designers',
  'Flash sale promotion - 50% off for limited time'
);

-- Sample 3: Designer Spotlight Announcement
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Featured Designer Spotlight',
  'Meet our top-rated designers! Connect with verified professionals who have completed 100+ successful projects.',
  'announcement',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  NULL,
  'all',
  ARRAY['homepage'],
  3,
  '#1f2937',
  '#f3f4f6',
  'View Designers',
  '/designers',
  'Announcement about featured designers'
);

-- Sample 4: Free Consultation Offer
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Free 15-Minute Consultation',
  'Not sure what you need? Get a free 15-minute consultation with our design experts to discuss your project.',
  'offer',
  'free_service',
  0.00,
  'FREE15',
  0.00,
  0.00,
  200,
  now(),
  now() + interval '14 days',
  'customers',
  ARRAY['homepage', 'services'],
  7,
  '#ffffff',
  '#7c3aed',
  'Book Free Consultation',
  '/contact',
  'Free consultation offer for new customers'
);

-- Sample 5: Designer Earnings Boost
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Designers: Earn More This Month!',
  'Join our platform and start earning from your design skills. We take only 10% commission - the lowest in the industry!',
  'announcement',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  NULL,
  'designers',
  ARRAY['homepage'],
  4,
  '#ffffff',
  '#059669',
  'Join as Designer',
  '/auth',
  'Promotion for designers to join the platform'
);

-- Sample 6: Holiday Special
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Holiday Special - 30% Off',
  'Celebrate the holidays with our special offer! Get 30% off on all design services. Perfect time to refresh your brand!',
  'discount',
  'percentage',
  30.00,
  'HOLIDAY30',
  800.00,
  1500.00,
  75,
  now(),
  now() + interval '21 days',
  'all',
  ARRAY['homepage', 'designers', 'services', 'about'],
  8,
  '#ffffff',
  '#ea580c',
  'Get Holiday Discount',
  '/designers',
  'Holiday special promotion - 30% off'
);

-- Sample 7: Popup Announcement
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'New Feature: Real-time Collaboration',
  'We just launched real-time collaboration tools! Design with your designer in real-time using our advanced video and screen sharing features.',
  'popup',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  now() + interval '7 days',
  'all',
  ARRAY['homepage'],
  9,
  '#1f2937',
  '#dbeafe',
  'Learn More',
  '/how-to-use',
  'Popup announcement about new collaboration features'
);

-- Sample 8: Banner Promotion
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_image_url,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Professional Design Services',
  'Transform your business with professional design services. From logos to complete brand identities, we have you covered.',
  'banner',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  NULL,
  'all',
  ARRAY['homepage', 'services'],
  2,
  'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=400&fit=crop',
  '#ffffff',
  '#1e40af',
  'Explore Services',
  '/services',
  'Banner promotion for professional design services'
);

-- Sample 9: Image Banner with Upload
INSERT INTO public.promotions (
  title,
  description,
  promotion_type,
  discount_type,
  discount_value,
  discount_code,
  min_order_amount,
  max_discount_amount,
  usage_limit,
  start_date,
  end_date,
  target_audience,
  display_location,
  priority,
  banner_image_url,
  banner_text_color,
  banner_background_color,
  cta_text,
  cta_url,
  admin_notes
) VALUES (
  'Creative Design Solutions',
  'Unlock your creative potential with our expert designers. Get custom solutions tailored to your brand.',
  'banner',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  now(),
  NULL,
  'all',
  ARRAY['homepage'],
  1,
  'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=400&fit=crop',
  '#ffffff',
  '#7c2d12',
  'Start Your Project',
  '/designers',
  'Creative design banner with uploaded image'
);
